# Generated by Django 3.1.7 on 2021-03-08 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xlogs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='topic',
            new_name='category',
        ),
    ]
